In [1]:
import numpy as np

In [14]:
# creating numpy array from list

In [2]:
x=np.array([1,2,3,4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
print(x)

[1 2 3 4]


In [5]:
print(type(x))

<class 'numpy.ndarray'>


In [13]:
#printing the dimension of the array

print(x.shape)

(4,)


In [7]:
y=np.array([[1,2],[3,4]])

In [9]:
print(y)
print("shape: ",y.shape)

[[1 2]
 [3 4]]
shape:  (2, 2)


In [10]:
 #printing thr dimension of the numpy array

z=np.array([[1+0.j,2+5.j]])

In [11]:
print(z)

[[1.+0.j 2.+5.j]]


In [12]:
print(z.shape)

(1, 2)


In [15]:
 #creating numpy array of zeros , of dimension (2,3)

a=np.zeros((2,3))

In [16]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
print(a.shape)

(2, 3)


In [18]:
#creating numpy array of ones , of dimension 
# (2,3) and integer type

b=np.ones((3,3))

In [19]:
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
print(b.shape)

(3, 3)


In [24]:
# identity matrix
d=np.eye(5)

In [25]:
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
#similar to Range function

e=np.arange(9)
print(e)

[0 1 2 3 4 5 6 7 8]


In [29]:
e=np.arange(9,30)
print(e)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [31]:
e = np.arange(8,100,8)
print(e)

[ 8 16 24 32 40 48 56 64 72 80 88 96]


In [41]:
# It create intervals

f=np.linspace(1,15,6)
print(f)

[ 1.   3.8  6.6  9.4 12.2 15. ]


In [42]:
#creating a numpy array 
#having dimension (3,4) with random elements

g=np.random.random((3,4))
print(g)

[[0.65758859 0.83577422 0.80899943 0.36328981]
 [0.47663924 0.3950664  0.21438467 0.23833427]
 [0.14936033 0.94569106 0.14721363 0.37256408]]


In [45]:
#reshaping the (3,4) array to (2,2,3)

h=g.reshape(2,2,3)

In [46]:
print(h)

[[[0.65758859 0.83577422 0.80899943]
  [0.36328981 0.47663924 0.3950664 ]]

 [[0.21438467 0.23833427 0.14936033]
  [0.94569106 0.14721363 0.37256408]]]


In [59]:
# numpy range with index

x=np.arange(12)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [51]:
print(x[3])

3


In [52]:
print(x[-2])

10


In [60]:
x.resize(3,5) # resizing arra to matrix

In [61]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0  0  0]]


In [71]:
print(x[0][0])
print(x[1][0])
print(x[2][1])
print(x[0][3])

0
5
11
3


In [73]:
# slicing

y = np.arange(1,15)
print(y)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [74]:
print(y[1:6])
print(y[:7])
print(y[7:])

[2 3 4 5 6]
[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [77]:
print(y[-3:])
print(y[-2:])
print(y[-6:])

[12 13 14]
[13 14]
[ 9 10 11 12 13 14]


In [80]:
print(y[3:-3])   ## start from  3 and stop 3 count from back

[ 4  5  6  7  8  9 10 11]


In [81]:
print(y[::2])

[ 1  3  5  7  9 11 13]


In [82]:
print(y[::3])

[ 1  4  7 10 13]


In [83]:
print(y[2::])

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [88]:
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [89]:
y = np.arange(1,26)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [90]:
print(y.reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [91]:
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [94]:
y=y.reshape(5,5)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [98]:
print(y[:5],"\n")

print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [99]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [100]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [101]:
print(y[:,-1])

[ 5 10 15 20 25]


In [102]:
print(y[::,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [103]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [104]:
print(y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [105]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [106]:
print(a+b)

[ 7  9 11 13 15]


In [110]:
print(b-a)
print(a*b)
print(a**2)

[5 5 5 5 5]
[ 6 14 24 36 50]
[ 1  4  9 16 25]


In [111]:
print(a>3)

[False False False  True  True]


In [113]:
a=np.arange(0,4).reshape((2,2))

In [114]:
print(a)

[[0 1]
 [2 3]]


In [115]:
b=np.eye(2)

In [116]:
print(b)

[[1. 0.]
 [0. 1.]]


In [117]:
print(a*b) ####not gen way for mul

[[0. 0.]
 [0. 3.]]


In [118]:
##Matrix multiplication

print(np.dot(a,b))

[[0. 1.]
 [2. 3.]]


In [119]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [120]:
print(x.sum())

45


In [123]:
print(x.sum(axis=0))
print(x.sum(axis=1))

[12 15 18]
[ 6 15 24]


In [124]:
x = np.arange(1,19).reshape(3,3,2)

In [125]:
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [126]:
print(x.sum(axis=1))

[[ 9 12]
 [27 30]
 [45 48]]


In [127]:
x = np.arange(1,10).reshape(3,3)

In [128]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [129]:
print(x.max())

9


In [131]:
print(x.max(axis=1))
print(x.max(axis=0))

[3 6 9]
[7 8 9]


In [133]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
